### ISSUE TITLE
Prevent autoopen field until one-by-one answered

### ISSUE THREAD

**Issue by talkael** [AnKing-Memberships/AnKing-Note-Types#101]
the auto open fields still opens fields in one by one before answering the whole note. Would be nice if it only is revealed after answering just like how the extra field was fixed

**Comment by AnKingMed** [comment]
@BlueGreenMagick is this possible?

**Comment by talkael** [comment]
Any updates about this?

**Comment by AnKingMed** [comment]
@BlueGreenMagick will you have time to look into this at all?

**Comment by SeanSmith14** [comment]
@AnKingMed @BlueGreenMagick Sorry if I have no etiquette, this is my first post on GitHub:

I have a solution that seems functional (literally just wrote it, haven't tested it in most scenarios). It integrates with current functionality by utilizing the "ButtonAutoReveal" variable. It works very similarly to the already existing method for hiding/revealing the "Extra" field and is called at the same time:

```js
const hideAllCloze = function(initial) {
  /*
    32 lines of unaltered code
  */
  const extra = document.getElementById("extra");
  if (extra) {
    extra.classList.add("hidden");
  }

  // EDITS
  for (let [k,v] of Object.entries(ButtonAutoReveal)) {
    if (v) {
      var elem = document.querySelectorAll(`[data-name="${k}"]`)[0]
      elem.getElementsByClassName("hints")[0].classList.add("hidden")
      elem.getElementsByTagName("button")[0].classList.remove("expanded-button")
    }
   }
  // END EDITS
}
```

```js
const maybeRevealExtraField = () => {
  let elems = document.querySelectorAll(".cloze-hidden")
  if (elems.length == 0) {
    const extra = document.getElementById("extra")
    if (extra) {
      extra.classList.remove("hidden")
    }
    // EDITS
    for (let [k,v] of Object.entries(ButtonAutoReveal)) {
      if (v) {
        var elem = document.querySelectorAll(`[data-name="${k}"]`)[0]
        elem.getElementsByClassName("hints")[0].classList.remove("hidden")
        elem.getElementsByTagName("button")[0].classList.add("expanded-button")
      }
    }
    // END EDITS
  }
}
```

One change that could improve efficiency of the last code block would be to search for elements by class using "hints hidden" instead of looping over ButtonAutoReveal again, but I haven't had time to try this.


The last bit that's needed was html class styling that could be easily added and removed, again similar to how the "Extra" field is hidden/revealed:
```html
<style>
.hints.hidden {
  display: none !important;
}
</style>
```

**Comment by AnKingMed** [comment]
@abdnh Do you want to look into this?  I think @BlueGreenMagick is out of commission for a bit

**Comment by abdnh** [comment]
Thanks @Quaidge
I went for a similar solution. Let us know if you notice any issues.
