### ISSUE TITLE
AnKing cloze One by One Notetype false layout

### ISSUE THREAD

**Issue by roesnerh** [AnKing-Memberships/AnKing-Note-Types#122]
Note Type: Anking Note Types (easy Customization) - cloze One by One

Problem description: Since the latest update the cloze One by One Notetype displays wrongly during review. Somehow I cannot change it. It looks chaotically like this:

<img width="1452" alt="Screenshot 2023-03-18 at 09 37 30" src="https://user-images.githubusercontent.com/128135517/226094959-897e2f67-1b2b-4c2a-a47d-f47b1bd69f36.png">

When editing it it looks right:

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/128135517/226094978-8da98925-be6f-4eed-82b6-236f4f4ee564.png">

Checklist

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

Anki version: 2.1.58

Operating system: MacOS,  Ventura 13.2.1

Error message: none

**Comment by AnKingMed** [comment]
As in the formatting is funky with line breaks and stuff?  Can you export this one note for us? (You'll need to zip it to attach here)

Did this only start happening after the last update?

**Comment by adildahlan** [comment]
Hello! I am experiencing this problem as well. Only happened after downloading AnKing Note Types (Easy Customization) add on. This problem is also with cards that do not have the on One By One enabled. All my cards are now messed up. I hope you could fix it. Many thanks!

**Comment by adildahlan** [comment]
I am trying to debug this. I downloaded the old release of AnkingOverhaul (https://github.com/AnKing-Memberships/AnKing-Note-Types/releases/tag/AnKingOverhaul-c3f6e55). Then I copied my text into that card and it was working perfectly (as shown below)! 
![image](https://user-images.githubusercontent.com/65319353/226108578-d9a975f2-0432-42a6-8d2c-83841fec6661.png)

This is a problem in the latest release only (as shown below)
![image](https://user-images.githubusercontent.com/65319353/226108626-31b65425-c65b-4057-be9c-7ae4d81fcc89.png)

In the mean time, Is there a way for me to revert all my AnkingOverhaul cards to release 1.0 as opposed to 1.1?

Many thanks!

**Comment by roesnerh** [comment]
Yes, exactely. The funky formatting happened after the latest update. Before that everything was working fine.

Here ist the zip file with the note:

[AnKing cloze OnebyOne.apkg.zip](https://github.com/AnKing-Memberships/AnKing-Note-Types/files/11010480/AnKing.cloze.OnebyOne.apkg.zip)

**Comment by RisingOrange** [comment]
@AnKingMed The weird formatting is caused by this css for styling lists: 
https://github.com/AnKing-Memberships/AnKing-Note-Types/blob/d69a46b2b7d050a3ae2ebfa61423c7d227bd8b98/src/notetypes/AnKing/Styling.css#L266-L290
It was added a year ago in this PR: https://github.com/AnKing-Memberships/AnKing-Note-Types/pull/56.
The purpose of this change was to improve the formatting of lists. I think that most of the styling makes sense, I would just remove the `display: inline-block` (and make another small change to the margin styling). With these changes the  card shared by @roesnerh looks like this:
![CopyQ kTavjG](https://user-images.githubusercontent.com/31575114/226168828-2f6abaa2-7fbf-4594-95f1-123ede8cacab.png)
Which is the same as with version 1.0 of the note type, except that the list is now centered on screen. What do you think, should I adapt the list styling like this?

Here is the list styling after my suggested changes:
```css
/* ~~~~~~~~~ LISTS ~~~~~~~~~ */
ul {
  padding-left: 40px;
  max-width: 50%;
  margin-left: auto;
  margin-right: auto;
  text-align: left;
}
ol {
  padding-left: 40px;
  max-width: 50%;
  margin-left: auto;
  margin-right: auto;
  text-align: left;
}
.mobile ul {
  text-align: left; 
  max-width: 100%;
}
.mobile ol {
  text-align: left; 
  max-width: 100%;
}
```

**Comment by AnKingMed** [comment]
That looks pretty good to me as long as there's no real benefit of the in-line-block

**Comment by AnKingMed** [comment]
Sounds good to me. Let's go ahead and make the change

**Comment by RisingOrange** [comment]
I updated the note types and published a new version of the add-on on AnkiWeb.

@roesnerh, @adildahlan The problem should be solved once you download the add-on update and then let it update the note types.

**Comment by adildahlan** [comment]
Thanks guys!

With the latest update, my card looks as such
![image](https://user-images.githubusercontent.com/65319353/226211712-95ac1854-ba9f-4072-8e2b-591069d685dd.png)

Whereas before it used to look as such 
![image](https://user-images.githubusercontent.com/65319353/226211729-aa8c0d8e-cb4c-4179-9cf4-174891498f83.png)

I wonder why the nested lists don't look as good (too indented) and the width of the card is not the whole card as opposed to how it used to look. I am not familiar with css...

**Comment by RisingOrange** [comment]
I guess the list styling is a matter of preference. 

@AnKingMed We could add a checkbox option for customizing list styling called `Center lists`. What do you think?

**Comment by adildahlan** [comment]
Hello!

Sorry, i think i didn't explain my issue clearly. 

In the image, below, you can see the indented bullet point is too indented, shown with the red arrow (compared to how it used to be before).
Also, the card is now not as wide as it used to be, the text is limited between the two blue lines (whereas before, it used to be as wide as the window, which allows for long sentences).

![226211712-95ac1854-ba9f-4072-8e2b-591069d685dd](https://user-images.githubusercontent.com/65319353/226213149-dfe3567d-aa49-420f-98b4-69c348f2620d.jpg)

I hope you can fix this to how it used to be before, thank you!

**Comment by RisingOrange** [comment]
@adildahlan I see. I'm not sure if more people prefer the way it looked previously or the way it looks now. 
If people prefer the old styling in general, we can change it back for everyone. Either way we could provide a simple checkbox option that let's you configure how you want lists to be styled:
 - centered in the middle of the screen 
 - or not

**Comment by adildahlan** [comment]
I see.

I think there is something funny happening with the indented pullet points. The left and right margins for the indented bullet points aer very different compared to the parent bullet, shown by the red and blue vertical lines. 

![226211712-95ac1854-ba9f-4072-8e2b-591069d685dd 2](https://user-images.githubusercontent.com/65319353/226215965-9ae8f9b2-03fc-4c65-a245-1582d0d410df.jpg)

**Comment by RisingOrange** [comment]
@adildahlan If you want you can for now just remove these lines of css from the Styling tab for the AnKing note type:

```css
/* ~~~~~~~~~ LISTS ~~~~~~~~~ */
ul {
  padding-left: 40px;
  max-width: 50%;
  margin-left: auto;
  margin-right: auto;
  text-align: left;
}
ol {
  padding-left: 40px;
  max-width: 50%;
  margin-left: auto;
  margin-right: auto;
  text-align: left;
}
.mobile ul {
  text-align: left; 
  max-width: 100%;
}
.mobile ol {
  text-align: left; 
  max-width: 100%;
}
```

What you have to do in order to do this:
- Go to Anki main window -> Tools -> Manage note types -> Choose the AnKing note type -> Cards 
- Select the Styling tab 
- Search for "LISTS" in the search bar and delete all the lines mentioned above

If you delete too much you can reset the note types, so don't worry too much about breaking things while editing the note type. This can be done by using the `Reset` button in this window:
![image](https://user-images.githubusercontent.com/31575114/226215967-c06379d4-1a19-459e-a892-d0a726f701a6.png)

**Comment by adildahlan** [comment]
@RisingOrange THANK YOU! You are an absolute legend! It's perfect now!

![image](https://user-images.githubusercontent.com/65319353/226216290-0ef609de-2a67-4bc6-a01c-065246171d4b.png)

**Comment by AnKingMed** [comment]
> I think there is something funny happening with the indented pullet points. The left and right margins for the indented bullet points aer very different compared to the parent bullet, shown by the red and blue vertical lines.

@RisingOrange any ideas for a solution to this?

The checkbox option sounds reasonable

**Comment by roesnerh** [comment]
Thanks a lot everyone! Now everything looks fine again! :)

**Comment by RisingOrange** [comment]
@AnKingMed 

> I think there is something funny happening with the indented pullet points. The left and right margins for the indented bullet points are very different compared to the parent bullet, shown by the red and blue vertical lines.

Fixed this now in https://github.com/AnKing-Memberships/AnKing-Note-Types/commit/137fdb2f4fc5afcba947ed3f46e64dcfeff80e53. This version is now on AnkiWeb.

Now the indentations of child bullet points look like this:
![image](https://user-images.githubusercontent.com/31575114/226578424-b60edaa8-57d3-4751-9a0c-d00571db5833.png)

@adildahlan  
When you update the note types to this version, the changes you made manually to the list styling will be reset. The difference will be that lists will be in the center of the card. (The indentation of child bullet points won't be as weird as previously, it will be as shown in the image above.) 
Is it very important for you that lists start on the very left of the screen?

**Comment by adildahlan** [comment]
Perfect! I personally prefer left-justified lists, it's easier to read.

**Comment by AnKingMed** [comment]
@RisingOrange im ok with adding a toggle for center or left justified lists

**Comment by adildahlan** [comment]
> Yesterday, I noticed that the one by one does not work when the cloze has an indented list within it.
> 
> The following card <img alt="image" width="874" src="https://user-images.githubusercontent.com/65319353/226596721-3cbd138a-d63f-41a0-aec1-884e8227091c.png">
> 
> Shows as such (before me showing any of the answers) <img alt="image" width="2000" src="https://user-images.githubusercontent.com/65319353/226596860-bfbc7e7d-0fe0-46d0-b8a6-d3fb21ed3771.png">
> 
> This only happens with the one by one option enabled. Whereas when I disable it, it works. Though I really like the one by one feature and it would be great if we can use it with it.

Hello @RisingOrange, 
I hope you are doing well,
I am just flagging this in case it was missed amongst the other comments. Is there any way this could be fixed? It is quite annoying because I mainly study through forming one big flashcard per topic and i use the one-by-one to go through it all at once. I hope you could help me figure it out. 
Many thanks!
Adil

**Comment by RisingOrange** [comment]
Hello @adildahlan!
I'm not sure what you mean when you say that the card doesn't work when the One by one feature is disabled. Does the text not get revealed when you click on the crown icon? I tested this and it is working for me.
If you want to preserve the structure of the list, you can use clozes like this:
<img src="https://user-images.githubusercontent.com/31575114/230595469-2cb07c94-abad-41e2-9e2b-650f20d3250d.png" width="500" />
<img src="https://user-images.githubusercontent.com/31575114/230595429-1afe1696-39fe-4506-b873-4f77ae484096.png" width="500" />

**Comment by adildahlan** [comment]
Hello @RisingOrange !
Thanks for getting back to me!
Sorry, I should have explained it better. The cloze I have for the "treatments", does not work; it does not hide the text in it. When I open the card to study it, the text is already revealed. 
Whereas the cloze for the "types" does work. I suspect it is because the "treatments" cloze has indented bullet points within it. Whereas the "types" cloze does not.
It might be a simple bug, but I am not quite familiar with the code to fix it. I hope you could have a look at it, many thanks!

**Comment by RisingOrange** [comment]
I understand what you mean now. Can you send me the html contents of the `Text` field of the note where this problem occurs? I tried to reproduce the problem and couldn't do it. You can toggle the html editor using the `<>` button in the upper right of the field:
<img src="https://user-images.githubusercontent.com/31575114/230624829-debb30f0-4872-4e4b-9e1b-a9ce6f6ffa25.png" width="500" /> 

Here is how it looks for me:
<img src="https://user-images.githubusercontent.com/31575114/230624719-d353bc98-db3d-4030-bc4e-d4aa7bdb4abc.png" width="500" />
<img src="https://user-images.githubusercontent.com/31575114/230623496-f0a7ebbf-e682-44da-b7af-fd7142f44e4f.png" width="500" />

**Comment by adildahlan** [comment]
Thank you! There you go!
<img width="950" alt="image" src="https://user-images.githubusercontent.com/65319353/230626715-6ee4fa73-f0a2-47f5-94ca-fb7dae005120.png">
Here's the HTML
<b>HTN:</b><br><ul><li>Treatment {{c1::</li><ul><li>Diuretics&nbsp;<ul><li>Loop diuretics</li><li>Thiazide diuretics</li></ul></li><li>ACE Inhibitors</li><li>Ca2+ channel blockers}}</li></ul><li>Types:{{c1::&nbsp;<ul><li>Primary</li><li>secondary}}</li></ul></li></ul>

**Comment by RisingOrange** [comment]
@adildahlan You are right, the wrong alignment is caused by the same reason, which is that the `</li>` html tags and `}}` are in the wrong places.

This the formatted html of your note:
```html
<b>HTN:</b><br>
<ul>
    <li>Treatment {{c1::</li>
    <ul>
        <li>Diuretics&nbsp;<ul>
                <li>Loop diuretics</li>
                <li>Thiazide diuretics</li>
            </ul>
        </li>
        <li>ACE Inhibitors</li>
        <li>Ca2+ channel blockers}}</li>
    </ul>
    <li>Types:{{c1::&nbsp;<ul>
            <li>Primary</li>
            <li>secondary}}</li>
        </ul>
    </li>
</ul>
```

This is the fixed version:
```html
HTN<b>:</b><br>
<ul>
    <li>Treatment: {{c1::
        <ul>
            <li>Diuretics
                <ul>
                    <li>Loop diuretics</li>
                    <li>Thiazide diuretics</li>
                </ul>
            </li>
            <li>ACE Inhibitors</li>
            <li>Ca2+ channel blockers</li>
        </ul>}}
    </li>
    <li>Types: {{c1::<ul>
            <li>Primary</li>
            <li>secondary</li>
      </ul>}}
    </li>
</ul>
<ul>
</ul>
```

The fixed version of the note shows up like this (it also works with one-by-one enabled):
<img src="https://user-images.githubusercontent.com/31575114/230641366-dd3f2cfe-dc1d-4ce2-a8d9-7ac197a374d6.png" width="500" />

Sorry, but I have no general solution to this. It seems like currently the solution is to edit the html of notes that have nested lists by hand to make sure that clozes work properly.
