### ISSUE TITLE
Updating Anking Note Types undos customization from front and back card edits

### ISSUE THREAD

**Issue by AnkiUser11764** [AnKing-Memberships/AnKing-Note-Types#139]
#### Problem description

Whenever it's updated, it resets my "back card" edits. I have to go back and change what values I've set as "True" and "False" for Pixorize, Picnomic, First Aid, etc

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ x] I've tried to disable add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54 (b6a7760c)
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Mac 13.3.1 (a)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
@RisingOrange or @abdnh can you look into if it's possible to keep user settings? 

This user also mentioned that if they click "no" on the would you like to update popup, it still pops up frequently. I wonder if that's a bug?

**Comment by RisingOrange** [comment]
@AnkiUser11764 Sorry for the inconvenience, there was indeed a bug in a previous version of the add-on that caused modifications to be reset when updating the note types. On the newest version this shouldn't happen anymore. 
Can you try to update the note type to the newest version? I think this will solve both of your problems. I'm assuming you didn't do that yet and are getting the update reminder dialog because of this. To be safe, you can create a backup of your collection first, update the note types and if your changes are reset you can restore your collection from the backup. Here's more information on how to create backups and restore your collection from them: https://docs.ankiweb.net/backups.html#manual-colpkg-backups

I'd recommend to:
- Make sure you have the newest version of the add-on installed by checking for updates (Tools -> Add-ons -> Check for updates, if there's an update, restart Anki after installing it)
- Create a backup
- Update the note types (AnKing -> AnKing Note Types -> Update note types)
- Check if your note type modifications are still there

If your settings were reset, you can go back to the previous state of the collection from the backup, but I think that won't be necessary.
Please update me on how it goes.

**Comment by AnKingMed** [comment]
Thanks for fixing that @RisingOrange !
